import type { ProjectContext } from '../core/context.js';
import type { AcceptanceCriterion, Prd, PrdPhase, PrdStory } from './prd-schema.js';

type StoryInput = Omit<PrdStory, 'id'>;

function ac(description: string): AcceptanceCriterion {
  return { description };
}

function prefixedStories(
  inputs: StoryInput[],
  phase: number,
  prefix: string,
): PrdStory[] {
  return inputs.map((story, i) => ({
    ...story,
    id: `P${phase}-${prefix}-${String(i + 1).padStart(3, '0')}`,
  }));
}

/**
 * Generates a prd.json for the scaffolded Flutter project.
 * Stories are organized into three phases:
 *   Phase 1 - Core app setup and basic navigation
 *   Phase 2 - Module-specific features (conditional on enabled modules)
 *   Phase 3 - Integration and end-to-end testing
 */
export function generatePrd(context: ProjectContext): string {
  const phase1Stories = prefixedStories(buildPhase1Inputs(context), 1, 'CORE');
  const phase1Ids = phase1Stories.map((s) => s.id);
  const phase2Stories = buildPhase2Stories(context, phase1Ids);
  const phase3Stories = buildPhase3Stories(context, phase1Ids, phase2Stories);

  const phases: PrdPhase[] = [
    {
      phase: 1,
      title: 'Core Setup',
      description: 'Core app structure, routing, and state management',
    },
    {
      phase: 2,
      title: 'Module Features',
      description: 'Module-specific features conditional on enabled configuration',
    },
    {
      phase: 3,
      title: 'Integration & Quality',
      description: 'Integration testing and final quality audit',
    },
  ];

  const prd: Prd = {
    version: '2.0.0',
    project: context.projectName,
    generatedAt: new Date().toISOString(),
    phases,
    stories: [...phase1Stories, ...phase2Stories, ...phase3Stories],
  };

  return JSON.stringify(prd, null, 2) + '\n';
}

function buildPhase1Inputs(context: ProjectContext): StoryInput[] {
  return [
    {
      phase: 1,
      priority: 'P0',
      title: 'Setup Clean Architecture project structure',
      description: `Verify and finalize the scaffolded project structure for ${context.projectName}. Ensure all directories follow Clean Architecture conventions with domain, data, and presentation layers per feature. Configure analysis_options.yaml with appropriate lint rules.`,
      storyPoints: 3,
      dependencies: [],
      acceptanceCriteria: [
        ac('`lib/features/` directory exists with at minimum a `home` feature'),
        ac('Each feature contains `domain/`, `data/`, and `presentation/` subdirectories'),
        ac('`lib/core/` contains router, theme, and providers directories'),
        ac('`flutter analyze` reports zero errors'),
        ac('`dart format --set-exit-if-changed .` passes'),
      ],
      passes: false,
    },
    {
      phase: 1,
      priority: 'P0',
      title: 'Configure go_router with type-safe routes',
      description:
        'Set up go_router in `lib/core/router/app_router.dart` using TypedGoRoute annotations. Define initial route to HomeRoute. Register the router as a Riverpod provider. Run build_runner to generate route code.',
      storyPoints: 5,
      dependencies: [],
      acceptanceCriteria: [
        ac('`lib/core/router/app_router.dart` exists with GoRouter configuration'),
        ac('Router is exposed as a Riverpod provider (`routerProvider`)'),
        ac('`HomeRoute` is defined with `@TypedGoRoute(path: \'/\')`'),
        ac('`lib/core/router/app_router.g.dart` is generated by build_runner'),
        ac('`flutter analyze` reports zero errors'),
      ],
      passes: false,
    },
    {
      phase: 1,
      priority: 'P0',
      title: 'Configure Riverpod ProviderScope and global providers',
      description:
        'Ensure `main.dart` wraps the app in `ProviderScope`. Set up `lib/core/providers/app_providers.dart` as a barrel export for all core providers. Verify the app boots without errors.',
      storyPoints: 3,
      dependencies: [],
      acceptanceCriteria: [
        ac('`main.dart` wraps `runApp` with `ProviderScope`'),
        ac('`lib/core/providers/app_providers.dart` exports core providers'),
        ac('App compiles and runs without errors'),
        ac('`flutter analyze` reports zero errors'),
      ],
      passes: false,
    },
    {
      phase: 1,
      priority: 'P1',
      title: `Implement ${context.projectName} home screen`,
      description: `Build the initial home screen at \`lib/features/home/presentation/pages/home_page.dart\`. The page should use ConsumerWidget and display the project name. Wire it up to the \`/\` route in app_router.`,
      storyPoints: 2,
      dependencies: [],
      acceptanceCriteria: [
        ac('`home_page.dart` exists and extends `ConsumerWidget`'),
        ac('Home page displays the app name or a welcome message'),
        ac('Route `/` navigates to the home page'),
        ac('Widget test in `test/features/home/` passes'),
        ac('`flutter test` passes all tests'),
      ],
      passes: false,
    },
  ];
}

function buildPhase2Stories(context: ProjectContext, phase1Ids: string[]): PrdStory[] {
  const stories: PrdStory[] = [];
  const coreSetupId = phase1Ids[0]; // P1-CORE-001
  const routerId = phase1Ids[1]; // P1-CORE-002
  const riverpodId = phase1Ids[2]; // P1-CORE-003

  if (context.modules.auth) {
    const provider = context.modules.auth.provider;
    const providerLabel =
      provider === 'firebase'
        ? 'Firebase Auth'
        : provider === 'supabase'
          ? 'Supabase Auth'
          : 'custom auth';
    const inputs: StoryInput[] = [
      {
        phase: 2,
        priority: 'P0',
        module: 'auth',
        title: `Implement authentication with ${providerLabel}`,
        description: `Build the auth feature in \`lib/features/auth/\` following Clean Architecture. Domain layer: \`AuthRepository\` interface and \`User\` entity. Data layer: \`${capitalize(provider)}AuthDataSource\` and \`AuthRepositoryImpl\`. Presentation layer: \`authRepositoryProvider\`, login page, register page. Add auth guard to go_router redirect.`,
        storyPoints: 8,
        dependencies: [coreSetupId, routerId, riverpodId],
        acceptanceCriteria: [
          ac('`lib/features/auth/domain/repositories/auth_repository.dart` defines `AuthRepository` interface'),
          ac('`lib/features/auth/domain/entities/user.dart` defines `User` entity with freezed'),
          ac('Auth repository implementation connects to ' + providerLabel),
          ac('`/login` and `/register` routes exist and render auth pages'),
          ac('Auth guard in go_router redirects unauthenticated users to `/login`'),
          ac('Unit tests for auth use cases pass'),
          ac('`flutter analyze` reports zero errors'),
        ],
        passes: false,
      },
    ];
    stories.push(...prefixedStories(inputs, 2, 'AUTH'));
  }

  if (context.modules.api) {
    const baseUrl = context.modules.api.baseUrl ?? 'API_BASE_URL env variable';
    const inputs: StoryInput[] = [
      {
        phase: 2,
        priority: 'P1',
        module: 'api',
        title: 'Implement API client with Dio and interceptors',
        description: `Configure a Dio HTTP client in \`lib/features/api/\`. Base URL: ${baseUrl}. Add interceptors for auth token injection, retry on transient failures, and request logging. Expose via \`dioClientProvider\`. Define \`ApiException\` for typed error handling.`,
        storyPoints: 5,
        dependencies: [coreSetupId, riverpodId],
        acceptanceCriteria: [
          ac('`dioClientProvider` is a Riverpod Provider returning a configured `Dio` instance'),
          ac('Auth interceptor injects Bearer token from auth state (if auth module is enabled)'),
          ac('Retry interceptor handles 5xx errors with exponential backoff'),
          ac('`ApiException` maps HTTP status codes to typed errors'),
          ac('Unit tests for interceptors pass'),
          ac('`flutter analyze` reports zero errors'),
        ],
        passes: false,
      },
    ];
    stories.push(...prefixedStories(inputs, 2, 'API'));
  }

  if (context.modules.database) {
    const engine = context.modules.database.engine;
    const engineLabel =
      engine === 'drift' ? 'Drift (SQLite)' : engine === 'hive' ? 'Hive' : 'Isar';
    const inputs: StoryInput[] = [
      {
        phase: 2,
        priority: 'P1',
        module: 'database',
        title: `Configure local database with ${engineLabel}`,
        description: `Set up ${engineLabel} in \`lib/features/database/\`. Define initial schema/collections. Expose database via \`databaseProvider\`. Add initialization in main.dart before runApp. Run build_runner to generate database code.`,
        storyPoints: 5,
        dependencies: [coreSetupId, riverpodId],
        acceptanceCriteria: [
          ac(`${engineLabel} is initialized before the app starts`),
          ac('`databaseProvider` exposes the database instance via Riverpod'),
          ac(
            engine === 'drift'
              ? '`AppDatabase` class with at least one table defined'
              : `${engineLabel} adapter/collection defined`,
          ),
          ac('build_runner generates code without conflicts'),
          ac('Unit test verifies database can be opened and written to'),
          ac('`flutter analyze` reports zero errors'),
        ],
        passes: false,
      },
    ];
    stories.push(...prefixedStories(inputs, 2, 'DB'));
  }

  if (context.modules.i18n) {
    const { defaultLocale, supportedLocales } = context.modules.i18n;
    const inputs: StoryInput[] = [
      {
        phase: 2,
        priority: 'P1',
        module: 'i18n',
        title: 'Implement internationalization with flutter_localizations',
        description: `Set up i18n in \`lib/core/l10n/\`. Create ARB files for: ${supportedLocales.join(', ')} (default: ${defaultLocale}). Run \`flutter gen-l10n\` to generate \`AppLocalizations\`. Update MaterialApp to include localization delegates.`,
        storyPoints: 3,
        dependencies: [coreSetupId],
        acceptanceCriteria: [
          ac(`ARB files exist for all supported locales: ${supportedLocales.join(', ')}`),
          ac('`AppLocalizations` is generated and available via `AppLocalizations.of(context)!`'),
          ac('MaterialApp includes `AppLocalizations.delegate` and `supportedLocales`'),
          ac('At minimum, app title and home screen greeting are localized'),
          ac('`flutter analyze` reports zero errors'),
        ],
        passes: false,
      },
    ];
    stories.push(...prefixedStories(inputs, 2, 'I18N'));
  }

  if (context.modules.theme) {
    const { seedColor, darkMode } = context.modules.theme;
    const seedNote = seedColor ? `seed color ${seedColor}` : 'default purple seed color';
    const inputs: StoryInput[] = [
      {
        phase: 2,
        priority: 'P1',
        module: 'theme',
        title: 'Implement Material 3 theme system',
        description: `Build the theme in \`lib/core/theme/app_theme.dart\` using Material 3 ColorScheme.fromSeed with ${seedNote}. ${darkMode ? 'Support both light and dark themes via `appThemeModeProvider`.' : 'Light theme only.'} Apply Google Fonts (Inter) as the default text theme.`,
        storyPoints: 3,
        dependencies: [coreSetupId],
        acceptanceCriteria: [
          ac('`AppTheme.light()` returns a `ThemeData` with Material 3 enabled'),
          ac(
            darkMode
              ? '`AppTheme.dark()` returns a dark `ThemeData`'
              : 'Light theme applied consistently',
          ),
          ac(
            darkMode
              ? '`appThemeModeProvider` toggles between light and dark modes'
              : 'Theme applied to MaterialApp',
          ),
          ac('Google Fonts Inter is applied as the text theme'),
          ac('`flutter analyze` reports zero errors'),
        ],
        passes: false,
      },
    ];
    stories.push(...prefixedStories(inputs, 2, 'THEME'));
  }

  if (context.modules.push) {
    const provider = context.modules.push.provider;
    const providerLabel =
      provider === 'firebase' ? 'Firebase Cloud Messaging' : 'OneSignal';
    const inputs: StoryInput[] = [
      {
        phase: 2,
        priority: 'P2',
        module: 'push',
        title: `Implement push notifications with ${providerLabel}`,
        description: `Configure ${providerLabel} in \`lib/features/push/\`. Request notification permissions at app startup. Handle foreground, background, and terminated state notifications. Expose push token via \`pushTokenProvider\`.`,
        storyPoints: 5,
        dependencies: [coreSetupId, riverpodId],
        acceptanceCriteria: [
          ac(`${providerLabel} is initialized before the app starts`),
          ac('Notification permission is requested on first launch'),
          ac('Foreground notification handler displays an in-app notification'),
          ac('Background/terminated notification tap navigates to correct screen'),
          ac('`pushTokenProvider` returns the device token as a Future<String?>'),
          ac('`flutter analyze` reports zero errors'),
        ],
        passes: false,
      },
    ];
    stories.push(...prefixedStories(inputs, 2, 'PUSH'));
  }

  if (context.modules.analytics) {
    const inputs: StoryInput[] = [
      {
        phase: 2,
        priority: 'P2',
        module: 'analytics',
        title: 'Implement analytics event tracking',
        description:
          'Create `AnalyticsService` abstraction in `lib/features/analytics/`. Implement a GoRouter observer that tracks screen views automatically. Provide `analyticsServiceProvider` for logging custom events. Log app open event on startup.',
        storyPoints: 3,
        dependencies: [coreSetupId, routerId],
        acceptanceCriteria: [
          ac('`AnalyticsService` interface defines `logEvent(name, params)` and `logScreen(name)`'),
          ac('GoRouter observer automatically tracks screen navigation'),
          ac('`analyticsServiceProvider` exposes the `AnalyticsService`'),
          ac('App open event is logged on startup'),
          ac('Unit tests mock `AnalyticsService` and verify event calls'),
          ac('`flutter analyze` reports zero errors'),
        ],
        passes: false,
      },
    ];
    stories.push(...prefixedStories(inputs, 2, 'ANLT'));
  }

  if (context.modules.cicd) {
    const providerLabel = context.modules.cicd.provider;
    const inputs: StoryInput[] = [
      {
        phase: 2,
        priority: 'P2',
        module: 'cicd',
        title: `Configure ${capitalize(providerLabel)} CI/CD pipeline`,
        description: `Set up CI/CD pipeline for ${capitalize(providerLabel)}. Pipeline should run on every push: (1) flutter analyze, (2) flutter test, (3) flutter build. Cache Flutter SDK and pub dependencies for speed.`,
        storyPoints: 2,
        dependencies: [coreSetupId],
        acceptanceCriteria: [
          ac(
            providerLabel === 'github'
              ? '`.github/workflows/ci.yml` exists and is valid YAML'
              : providerLabel === 'gitlab'
                ? '`.gitlab-ci.yml` exists and is valid YAML'
                : '`bitbucket-pipelines.yml` exists and is valid YAML',
          ),
          ac('Pipeline includes analyze, test, and build stages/jobs'),
          ac('Flutter pub cache is configured for fast runs'),
          ac('Pipeline triggers on push to main and pull requests'),
          ac('`flutter analyze` reports zero errors in CI config files'),
        ],
        passes: false,
      },
    ];
    stories.push(...prefixedStories(inputs, 2, 'CICD'));
  }

  if (context.modules.deepLinking) {
    const { scheme, host } = context.modules.deepLinking;
    const linkExample =
      scheme && host ? `${scheme}://${host}` : 'app://example.com';
    const inputs: StoryInput[] = [
      {
        phase: 2,
        priority: 'P2',
        module: 'deepLinking',
        title: 'Implement deep linking with app_links',
        description: `Configure deep links using \`app_links\` package. Handle Universal Links (iOS) and App Links (Android). Integrate with go_router for automatic route resolution. Example link: \`${linkExample}\`.`,
        storyPoints: 5,
        dependencies: [coreSetupId, routerId],
        acceptanceCriteria: [
          ac('`app_links` is initialized at app startup'),
          ac('Incoming deep links are forwarded to go_router for navigation'),
          ac(
            scheme
              ? `Custom scheme \`${scheme}://\` is handled`
              : 'Deep link scheme is configured in platform files',
          ),
          ac(
            host
              ? `Host \`${host}\` is configured for Universal/App Links`
              : 'Host is configured in platform-specific files',
          ),
          ac('Widget test verifies deep link navigation'),
          ac('`flutter analyze` reports zero errors'),
        ],
        passes: false,
      },
    ];
    stories.push(...prefixedStories(inputs, 2, 'LINK'));
  }

  return stories;
}

function buildPhase3Stories(
  context: ProjectContext,
  phase1Ids: string[],
  phase2Stories: PrdStory[],
): PrdStory[] {
  const enabledModules: string[] = [];
  if (context.modules.auth) enabledModules.push('auth');
  if (context.modules.api) enabledModules.push('api');
  if (context.modules.database) enabledModules.push('database');

  const allPrecedingIds = [...phase1Ids, ...phase2Stories.map((s) => s.id)];

  const inputs: StoryInput[] = [
    {
      phase: 3,
      priority: 'P1',
      title: 'Write integration tests for core user flows',
      description: `Write integration tests covering the main user journeys in ${context.projectName}. ${enabledModules.length > 0 ? `Test flows involving: ${enabledModules.join(', ')}.` : 'Test home screen navigation and basic app flows.'} Use \`integration_test\` package with \`flutter_test\`.`,
      storyPoints: 5,
      dependencies: allPrecedingIds,
      acceptanceCriteria: [
        ac('`integration_test/` directory exists with at least one integration test file'),
        ac('Tests cover the happy path for core user journeys'),
        ac('Tests use `WidgetTester` for UI interactions'),
        ac('`flutter test integration_test/` passes all tests'),
        ac('Test coverage report shows >70% coverage for presentation layer'),
      ],
      passes: false,
    },
    {
      phase: 3,
      priority: 'P2',
      title: 'Final quality audit and documentation',
      description: `Perform a final quality pass on all code in ${context.projectName}. Fix any remaining analyzer warnings. Ensure all public APIs have dartdoc comments. Verify README.md documents how to run the app and run tests.`,
      storyPoints: 2,
      dependencies: ['P3-QA-001'],
      acceptanceCriteria: [
        ac('`flutter analyze` reports zero errors AND zero warnings'),
        ac('`flutter test` passes all tests'),
        ac('`dart format --set-exit-if-changed .` passes'),
        ac('README.md includes setup instructions and how to run the app'),
        ac('All public provider declarations have dartdoc comments'),
      ],
      passes: false,
    },
  ];

  return prefixedStories(inputs, 3, 'QA');
}

function capitalize(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}
