import type { ProjectContext } from '../core/context.js';

interface PrdStory {
  id: string;
  phase: 1 | 2 | 3;
  priority: 'P0' | 'P1' | 'P2' | 'P3';
  title: string;
  description: string;
  acceptanceCriteria: string[];
  passes: false;
}

interface Prd {
  version: string;
  project: string;
  stories: PrdStory[];
}

/**
 * Generates a prd.json for the scaffolded Flutter project.
 * Stories are organized into three phases:
 *   Phase 1 - Core app setup and basic navigation
 *   Phase 2 - Module-specific features (conditional on enabled modules)
 *   Phase 3 - Integration and end-to-end testing
 */
export function generatePrd(context: ProjectContext): string {
  const rawStories = [
    ...generatePhase1Stories(context),
    ...generatePhase2Stories(context),
    ...generatePhase3Stories(context),
  ];

  // Assign sequential IDs
  const numbered: PrdStory[] = rawStories.map((story, index) => ({
    ...story,
    id: `S-${String(index + 1).padStart(3, '0')}`,
  }));

  const prd: Prd = {
    version: '1.0.0',
    project: context.projectName,
    stories: numbered,
  };

  return JSON.stringify(prd, null, 2) + '\n';
}

function generatePhase1Stories(context: ProjectContext): Omit<PrdStory, 'id'>[] {
  return [
    {
      phase: 1,
      priority: 'P0',
      title: 'Setup Clean Architecture project structure',
      description: `Verify and finalize the scaffolded project structure for ${context.projectName}. Ensure all directories follow Clean Architecture conventions with domain, data, and presentation layers per feature. Configure analysis_options.yaml with appropriate lint rules.`,
      acceptanceCriteria: [
        '`lib/features/` directory exists with at minimum a `home` feature',
        'Each feature contains `domain/`, `data/`, and `presentation/` subdirectories',
        '`lib/core/` contains router, theme, and providers directories',
        '`flutter analyze` reports zero errors',
        '`dart format --set-exit-if-changed .` passes',
      ],
      passes: false,
    },
    {
      phase: 1,
      priority: 'P0',
      title: 'Configure go_router with type-safe routes',
      description: 'Set up go_router in `lib/core/router/app_router.dart` using TypedGoRoute annotations. Define initial route to HomeRoute. Register the router as a Riverpod provider. Run build_runner to generate route code.',
      acceptanceCriteria: [
        '`lib/core/router/app_router.dart` exists with GoRouter configuration',
        'Router is exposed as a Riverpod provider (`routerProvider`)',
        '`HomeRoute` is defined with `@TypedGoRoute(path: \'/\')`',
        '`lib/core/router/app_router.g.dart` is generated by build_runner',
        '`flutter analyze` reports zero errors',
      ],
      passes: false,
    },
    {
      phase: 1,
      priority: 'P0',
      title: 'Configure Riverpod ProviderScope and global providers',
      description: 'Ensure `main.dart` wraps the app in `ProviderScope`. Set up `lib/core/providers/app_providers.dart` as a barrel export for all core providers. Verify the app boots without errors.',
      acceptanceCriteria: [
        '`main.dart` wraps `runApp` with `ProviderScope`',
        '`lib/core/providers/app_providers.dart` exports core providers',
        'App compiles and runs without errors',
        '`flutter analyze` reports zero errors',
      ],
      passes: false,
    },
    {
      phase: 1,
      priority: 'P1',
      title: `Implement ${context.projectName} home screen`,
      description: `Build the initial home screen at \`lib/features/home/presentation/pages/home_page.dart\`. The page should use ConsumerWidget and display the project name. Wire it up to the \`/\` route in app_router.`,
      acceptanceCriteria: [
        '`home_page.dart` exists and extends `ConsumerWidget`',
        'Home page displays the app name or a welcome message',
        'Route `/` navigates to the home page',
        'Widget test in `test/features/home/` passes',
        '`flutter test` passes all tests',
      ],
      passes: false,
    },
  ];
}

function generatePhase2Stories(context: ProjectContext): Omit<PrdStory, 'id'>[] {
  const stories: Omit<PrdStory, 'id'>[] = [];

  if (context.modules.auth) {
    const provider = context.modules.auth.provider;
    const providerLabel = provider === 'firebase' ? 'Firebase Auth' : provider === 'supabase' ? 'Supabase Auth' : 'custom auth';
    stories.push({
      phase: 2,
      priority: 'P0',
      title: `Implement authentication with ${providerLabel}`,
      description: `Build the auth feature in \`lib/features/auth/\` following Clean Architecture. Domain layer: \`AuthRepository\` interface and \`User\` entity. Data layer: \`${capitalize(provider)}AuthDataSource\` and \`AuthRepositoryImpl\`. Presentation layer: \`authRepositoryProvider\`, login page, register page. Add auth guard to go_router redirect.`,
      acceptanceCriteria: [
        '`lib/features/auth/domain/repositories/auth_repository.dart` defines `AuthRepository` interface',
        '`lib/features/auth/domain/entities/user.dart` defines `User` entity with freezed',
        'Auth repository implementation connects to ' + providerLabel,
        '`/login` and `/register` routes exist and render auth pages',
        'Auth guard in go_router redirects unauthenticated users to `/login`',
        'Unit tests for auth use cases pass',
        '`flutter analyze` reports zero errors',
      ],
      passes: false,
    });
  }

  if (context.modules.api) {
    const baseUrl = context.modules.api.baseUrl ?? 'API_BASE_URL env variable';
    stories.push({
      phase: 2,
      priority: 'P1',
      title: 'Implement API client with Dio and interceptors',
      description: `Configure a Dio HTTP client in \`lib/features/api/\`. Base URL: ${baseUrl}. Add interceptors for auth token injection, retry on transient failures, and request logging. Expose via \`dioClientProvider\`. Define \`ApiException\` for typed error handling.`,
      acceptanceCriteria: [
        '`dioClientProvider` is a Riverpod Provider returning a configured `Dio` instance',
        'Auth interceptor injects Bearer token from auth state (if auth module is enabled)',
        'Retry interceptor handles 5xx errors with exponential backoff',
        '`ApiException` maps HTTP status codes to typed errors',
        'Unit tests for interceptors pass',
        '`flutter analyze` reports zero errors',
      ],
      passes: false,
    });
  }

  if (context.modules.database) {
    const engine = context.modules.database.engine;
    const engineLabel = engine === 'drift' ? 'Drift (SQLite)' : engine === 'hive' ? 'Hive' : 'Isar';
    stories.push({
      phase: 2,
      priority: 'P1',
      title: `Configure local database with ${engineLabel}`,
      description: `Set up ${engineLabel} in \`lib/features/database/\`. Define initial schema/collections. Expose database via \`databaseProvider\`. Add initialization in main.dart before runApp. Run build_runner to generate database code.`,
      acceptanceCriteria: [
        `${engineLabel} is initialized before the app starts`,
        '`databaseProvider` exposes the database instance via Riverpod',
        engine === 'drift' ? '`AppDatabase` class with at least one table defined' : `${engineLabel} adapter/collection defined`,
        'build_runner generates code without conflicts',
        'Unit test verifies database can be opened and written to',
        '`flutter analyze` reports zero errors',
      ],
      passes: false,
    });
  }

  if (context.modules.i18n) {
    const { defaultLocale, supportedLocales } = context.modules.i18n;
    stories.push({
      phase: 2,
      priority: 'P1',
      title: 'Implement internationalization with flutter_localizations',
      description: `Set up i18n in \`lib/core/l10n/\`. Create ARB files for: ${supportedLocales.join(', ')} (default: ${defaultLocale}). Run \`flutter gen-l10n\` to generate \`AppLocalizations\`. Update MaterialApp to include localization delegates.`,
      acceptanceCriteria: [
        `ARB files exist for all supported locales: ${supportedLocales.join(', ')}`,
        '`AppLocalizations` is generated and available via `AppLocalizations.of(context)!`',
        'MaterialApp includes `AppLocalizations.delegate` and `supportedLocales`',
        'At minimum, app title and home screen greeting are localized',
        '`flutter analyze` reports zero errors',
      ],
      passes: false,
    });
  }

  if (context.modules.theme) {
    const { seedColor, darkMode } = context.modules.theme;
    const seedNote = seedColor ? `seed color ${seedColor}` : 'default purple seed color';
    stories.push({
      phase: 2,
      priority: 'P1',
      title: 'Implement Material 3 theme system',
      description: `Build the theme in \`lib/core/theme/app_theme.dart\` using Material 3 ColorScheme.fromSeed with ${seedNote}. ${darkMode ? 'Support both light and dark themes via `appThemeModeProvider`.' : 'Light theme only.'} Apply Google Fonts (Inter) as the default text theme.`,
      acceptanceCriteria: [
        '`AppTheme.light()` returns a `ThemeData` with Material 3 enabled',
        darkMode ? '`AppTheme.dark()` returns a dark `ThemeData`' : 'Light theme applied consistently',
        darkMode ? '`appThemeModeProvider` toggles between light and dark modes' : 'Theme applied to MaterialApp',
        'Google Fonts Inter is applied as the text theme',
        '`flutter analyze` reports zero errors',
      ],
      passes: false,
    });
  }

  if (context.modules.push) {
    const provider = context.modules.push.provider;
    const providerLabel = provider === 'firebase' ? 'Firebase Cloud Messaging' : 'OneSignal';
    stories.push({
      phase: 2,
      priority: 'P2',
      title: `Implement push notifications with ${providerLabel}`,
      description: `Configure ${providerLabel} in \`lib/features/push/\`. Request notification permissions at app startup. Handle foreground, background, and terminated state notifications. Expose push token via \`pushTokenProvider\`.`,
      acceptanceCriteria: [
        `${providerLabel} is initialized before the app starts`,
        'Notification permission is requested on first launch',
        'Foreground notification handler displays an in-app notification',
        'Background/terminated notification tap navigates to correct screen',
        '`pushTokenProvider` returns the device token as a Future<String?>',
        '`flutter analyze` reports zero errors',
      ],
      passes: false,
    });
  }

  if (context.modules.analytics) {
    stories.push({
      phase: 2,
      priority: 'P2',
      title: 'Implement analytics event tracking',
      description: 'Create `AnalyticsService` abstraction in `lib/features/analytics/`. Implement a GoRouter observer that tracks screen views automatically. Provide `analyticsServiceProvider` for logging custom events. Log app open event on startup.',
      acceptanceCriteria: [
        '`AnalyticsService` interface defines `logEvent(name, params)` and `logScreen(name)`',
        'GoRouter observer automatically tracks screen navigation',
        '`analyticsServiceProvider` exposes the `AnalyticsService`',
        'App open event is logged on startup',
        'Unit tests mock `AnalyticsService` and verify event calls',
        '`flutter analyze` reports zero errors',
      ],
      passes: false,
    });
  }

  if (context.modules.cicd) {
    const providerLabel = context.modules.cicd.provider;
    stories.push({
      phase: 2,
      priority: 'P2',
      title: `Configure ${capitalize(providerLabel)} CI/CD pipeline`,
      description: `Set up CI/CD pipeline for ${capitalize(providerLabel)}. Pipeline should run on every push: (1) flutter analyze, (2) flutter test, (3) flutter build. Cache Flutter SDK and pub dependencies for speed.`,
      acceptanceCriteria: [
        providerLabel === 'github' ? '`.github/workflows/ci.yml` exists and is valid YAML' : providerLabel === 'gitlab' ? '`.gitlab-ci.yml` exists and is valid YAML' : '`bitbucket-pipelines.yml` exists and is valid YAML',
        'Pipeline includes analyze, test, and build stages/jobs',
        'Flutter pub cache is configured for fast runs',
        'Pipeline triggers on push to main and pull requests',
        '`flutter analyze` reports zero errors in CI config files',
      ],
      passes: false,
    });
  }

  if (context.modules.deepLinking) {
    const { scheme, host } = context.modules.deepLinking;
    const linkExample = scheme && host ? `${scheme}://${host}` : 'app://example.com';
    stories.push({
      phase: 2,
      priority: 'P2',
      title: 'Implement deep linking with app_links',
      description: `Configure deep links using \`app_links\` package. Handle Universal Links (iOS) and App Links (Android). Integrate with go_router for automatic route resolution. Example link: \`${linkExample}\`.`,
      acceptanceCriteria: [
        '`app_links` is initialized at app startup',
        'Incoming deep links are forwarded to go_router for navigation',
        scheme ? `Custom scheme \`${scheme}://\` is handled` : 'Deep link scheme is configured in platform files',
        host ? `Host \`${host}\` is configured for Universal/App Links` : 'Host is configured in platform-specific files',
        'Widget test verifies deep link navigation',
        '`flutter analyze` reports zero errors',
      ],
      passes: false,
    });
  }

  return stories;
}

function generatePhase3Stories(context: ProjectContext): Omit<PrdStory, 'id'>[] {
  const enabledModules: string[] = [];
  if (context.modules.auth) enabledModules.push('auth');
  if (context.modules.api) enabledModules.push('api');
  if (context.modules.database) enabledModules.push('database');

  return [
    {
      phase: 3,
      priority: 'P1',
      title: 'Write integration tests for core user flows',
      description: `Write integration tests covering the main user journeys in ${context.projectName}. ${enabledModules.length > 0 ? `Test flows involving: ${enabledModules.join(', ')}.` : 'Test home screen navigation and basic app flows.'} Use \`integration_test\` package with \`flutter_test\`.`,
      acceptanceCriteria: [
        '`integration_test/` directory exists with at least one integration test file',
        'Tests cover the happy path for core user journeys',
        'Tests use `WidgetTester` for UI interactions',
        '`flutter test integration_test/` passes all tests',
        'Test coverage report shows >70% coverage for presentation layer',
      ],
      passes: false,
    },
    {
      phase: 3,
      priority: 'P2',
      title: 'Final quality audit and documentation',
      description: `Perform a final quality pass on all code in ${context.projectName}. Fix any remaining analyzer warnings. Ensure all public APIs have dartdoc comments. Verify README.md documents how to run the app and run tests.`,
      acceptanceCriteria: [
        '`flutter analyze` reports zero errors AND zero warnings',
        '`flutter test` passes all tests',
        '`dart format --set-exit-if-changed .` passes',
        'README.md includes setup instructions and how to run the app',
        'All public provider declarations have dartdoc comments',
      ],
      passes: false,
    },
  ];
}

function capitalize(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}
