import fs from 'fs-extra';
import path from 'node:path';
import type { ProjectContext } from '../core/context.js';

export async function writeSkills(context: ProjectContext, outputPath: string): Promise<void> {
  const skillsDir = path.join(outputPath, '.claude', 'skills');
  await fs.ensureDir(skillsDir);

  await Promise.all([
    fs.writeFile(path.join(skillsDir, 'flutter-patterns.md'), generateFlutterPatterns()),
    fs.writeFile(path.join(skillsDir, 'go-router-patterns.md'), generateGoRouterPatterns(context)),
    fs.writeFile(path.join(skillsDir, 'module-conventions.md'), generateModuleConventions()),
    fs.writeFile(path.join(skillsDir, 'prd.md'), generatePrdGuide()),
    fs.writeFile(path.join(skillsDir, 'security-review.md'), generateSecurityReview()),
    fs.writeFile(path.join(skillsDir, 'performance-check.md'), generatePerformanceCheck()),
    fs.writeFile(path.join(skillsDir, 'add-feature.md'), generateAddFeatureSkill(context)),
    fs.writeFile(path.join(skillsDir, 'quality-gate.md'), generateQualityGate()),
  ]);
}

function generateFlutterPatterns(): string {
  return [
    '# Flutter / Riverpod Patterns',
    '',
    '## Provider Naming Conventions',
    '',
    '- Providers are top-level `final` variables with a `Provider` suffix',
    '- Repository providers: `authRepositoryProvider`, `userRepositoryProvider`',
    '- State providers: `userNotifierProvider`, `authStateProvider`',
    '- Computed providers: `isLoggedInProvider`, `currentUserProvider`',
    '',
    '## Provider Types',
    '',
    '| Type | Use Case |',
    '|------|----------|',
    '| `Provider` | Computed values, repository instances, services |',
    '| `NotifierProvider` | Synchronous mutable state (Riverpod 2.0+) |',
    '| `AsyncNotifierProvider` | Async mutable state (Riverpod 2.0+) |',
    '| `FutureProvider` | One-shot async data (auto-disposes, caches) |',
    '| `StreamProvider` | Real-time streams (Firestore, WebSocket) |',
    '| `StateProvider` | Simple primitive state (bool, int, String) |',
    '',
    '## ref.watch vs ref.read',
    '',
    '- **`ref.watch()`**: Use inside `build()` methods and provider bodies. Re-builds when value changes.',
    '- **`ref.read()`**: Use inside callbacks, event handlers. Does NOT trigger rebuilds.',
    '- **`ref.listen()`**: Side effects in response to state changes (snackbars, navigation).',
    '',
    '## AsyncNotifier (preferred for Riverpod 2.0+)',
    '',
    '```dart',
    'final userProvider = AsyncNotifierProvider<UserNotifier, User?>(() {',
    '  return UserNotifier();',
    '});',
    '',
    'class UserNotifier extends AsyncNotifier<User?> {',
    '  @override',
    '  Future<User?> build() async {',
    '    return ref.watch(authRepositoryProvider).getCurrentUser();',
    '  }',
    '',
    '  Future<void> refresh() async {',
    '    state = const AsyncLoading();',
    '    state = await AsyncValue.guard(() =>',
    '      ref.read(authRepositoryProvider).getCurrentUser()',
    '    );',
    '  }',
    '}',
    '```',
    '',
    '## Provider Composition',
    '',
    '```dart',
    'final httpClientProvider = Provider<Dio>((ref) => Dio());',
    '',
    'final authDataSourceProvider = Provider<AuthRemoteDataSource>((ref) {',
    '  return AuthRemoteDataSourceImpl(ref.watch(httpClientProvider));',
    '});',
    '',
    'final authRepositoryProvider = Provider<AuthRepository>((ref) {',
    '  return AuthRepositoryImpl(ref.watch(authDataSourceProvider));',
    '});',
    '```',
    '',
    '## Freezed Sealed Union for State',
    '',
    '```dart',
    '@freezed',
    'sealed class AuthState with _$AuthState {',
    '  const factory AuthState.initial() = AuthStateInitial;',
    '  const factory AuthState.loading() = AuthStateLoading;',
    '  const factory AuthState.authenticated(User user) = AuthStateAuthenticated;',
    '  const factory AuthState.error(String message) = AuthStateError;',
    '}',
    '```',
    '',
    '## AsyncValue.when Error Handling',
    '',
    '```dart',
    'ref.watch(userProvider).when(',
    '  data: (user) => UserCard(user: user),',
    '  loading: () => const CircularProgressIndicator(),',
    '  error: (err, stack) => ErrorWidget(err.toString()),',
    ')',
    '```',
    '',
    '## Cache Refresh with ref.invalidate',
    '',
    '```dart',
    '// Force re-fetch from the network',
    'ref.invalidate(userProvider);',
    '',
    '// Invalidate a family member only',
    'ref.invalidate(userByIdProvider(userId));',
    '```',
    '',
    '## State Management Best Practices',
    '',
    '1. **Immutable state**: Use `freezed` for state classes to avoid mutation bugs',
    '2. **Single source of truth**: One provider owns each piece of state',
    '3. **Invalidation**: Use `ref.invalidate(provider)` to force a refresh',
    '4. **Family providers**: Use `.family` modifier for parameterized providers',
    '5. **Auto-dispose**: Use `.autoDispose` to clean up providers when not in use',
  ].join('\n');
}

function generateGoRouterPatterns(context: ProjectContext): string {
  const deepLinkingNote = context.modules.deepLinking
    ? [
        '',
        '## Deep Linking Integration',
        '',
        'This project has deep linking enabled. Routes are handled via `app_links`.',
      ].join('\n')
    : '';

  const authGuardNote = context.modules.auth
    ? [
        '',
        '## Auth Guards',
        '',
        '```dart',
        'GoRouter(',
        '  redirect: (context, state) {',
        '    final isLoggedIn = ref.read(isLoggedInProvider);',
        '    final isAuthRoute = state.matchedLocation.startsWith(\'/auth\');',
        '    if (!isLoggedIn && !isAuthRoute) return \'/auth/login\';',
        '    if (isLoggedIn && isAuthRoute) return \'/\';',
        '    return null;',
        '  },',
        ')',
        '```',
      ].join('\n')
    : '';

  return [
    '# go_router Patterns',
    '',
    '## Route Definition',
    '',
    'Routes are defined in `lib/core/router/app_router.dart` using TypedGoRoute for type-safe navigation.',
    '',
    '```dart',
    'part \'app_router.g.dart\';',
    '',
    '@TypedGoRoute<HomeRoute>(path: \'/\', routes: [',
    '  TypedGoRoute<ProfileRoute>(path: \'profile\'),',
    '])',
    '@immutable',
    'class HomeRoute extends GoRouteData {',
    '  const HomeRoute();',
    '',
    '  @override',
    '  Widget build(BuildContext context, GoRouterState state) => const HomePage();',
    '}',
    '```',
    '',
    '## Navigation',
    '',
    '```dart',
    '// Type-safe (preferred)',
    'const HomeRoute().go(context);',
    'ProfileRoute(userId: \'123\').push(context);',
    '```',
    authGuardNote,
    deepLinkingNote,
    '',
    '',
    '## ShellRoute with BottomNavigationBar',
    '',
    'Use `ShellRoute` for persistent UI (e.g., bottom nav bar) shared across nested routes:',
    '',
    '```dart',
    'GoRouter(',
    '  routes: [',
    '    ShellRoute(',
    '      builder: (context, state, child) => ScaffoldWithNav(child: child),',
    '      routes: [',
    '        GoRoute(path: \'/home\', builder: (_, __) => const HomePage()),',
    '        GoRoute(path: \'/search\', builder: (_, __) => const SearchPage()),',
    '        GoRoute(path: \'/profile\', builder: (_, __) => const ProfilePage()),',
    '      ],',
    '    ),',
    '  ],',
    ')',
    '```',
    '',
    '## Nested Route Pattern',
    '',
    'Nest child routes under a parent for deep linking and scoped navigation:',
    '',
    '```dart',
    '@TypedGoRoute<HomeRoute>(path: \'/\', routes: [',
    '  TypedGoRoute<PostRoute>(path: \'posts/:id\', routes: [',
    '    TypedGoRoute<CommentRoute>(path: \'comments\'),',
    '  ]),',
    '])',
    '```',
    '',
    '## Multiple Redirect Guards',
    '',
    '```dart',
    'GoRouter(',
    '  redirect: (context, state) {',
    '    // Guard 1: authentication',
    '    final isLoggedIn = ref.read(isLoggedInProvider);',
    '    if (!isLoggedIn && !state.matchedLocation.startsWith(\'/auth\')) return \'/auth/login\';',
    '    // Guard 2: onboarding',
    '    final hasProfile = ref.read(hasProfileProvider);',
    '    if (isLoggedIn && !hasProfile && state.matchedLocation != \'/onboarding\') return \'/onboarding\';',
    '    return null;',
    '  },',
    ')',
    '```',
    '',
    '## Adding a New Route',
    '',
    '1. Create a route class with `@TypedGoRoute` annotation',
    '2. Implement the `build()` method returning the page widget',
    '3. Run `dart run build_runner build --delete-conflicting-outputs`',
    '4. Update the parent route\'s `routes` list if it\'s a child route',
  ].join('\n');
}

function generateModuleConventions(): string {
  return [
    '# Module Conventions (Clean Architecture)',
    '',
    '## Directory Structure Per Feature',
    '',
    '```',
    'lib/features/<feature-name>/',
    '├── domain/',
    '│   ├── entities/          # Pure Dart models (use freezed)',
    '│   ├── repositories/      # Abstract repository interfaces',
    '│   └── usecases/          # Single-responsibility business operations',
    '├── data/',
    '│   ├── datasources/       # Remote (API) and local (DB) data sources',
    '│   ├── models/            # Data transfer objects with serialization',
    '│   └── repositories/      # Repository implementations',
    '└── presentation/',
    '    ├── pages/             # Full-screen UI (route targets)',
    '    ├── widgets/           # Reusable UI components',
    '    └── providers/         # Riverpod providers and state notifiers',
    '```',
    '',
    '## Layer Dependency Rules',
    '',
    '```',
    'Domain ← Data ← Presentation',
    '```',
    '',
    '- **Domain**: No dependencies on other layers or external packages',
    '- **Data**: Depends on Domain only (implements repository interfaces)',
    '- **Presentation**: Depends on Domain only (accesses Data via providers)',
    '',
    '## Cross-Feature Communication',
    '',
    'Features should NOT import from each other directly. Use:',
    '',
    '- **Providers**: Share state through Riverpod providers in `lib/core/providers/`',
    '- **Entities**: Share domain entities through `lib/core/domain/`',
    '- **Events**: Use streams or callbacks for loose coupling',
    '',
    '## Adding a New Feature',
    '',
    '1. Create feature directory following the structure above',
    '2. Start with Domain layer: entities, repository interfaces, use cases',
    '3. Add Data layer: models, data sources, repository implementation',
    '4. Add Presentation layer: providers, pages, widgets',
    '5. Register routes in `lib/core/router/app_router.dart`',
    '6. Run code generation: `dart run build_runner build --delete-conflicting-outputs`',
    '7. Write tests in `test/features/<name>/`',
  ].join('\n');
}

function generatePrdGuide(): string {
  return [
    '# Working with prd.json',
    '',
    '## Story Structure (PRD v2)',
    '',
    '```json',
    '{',
    '  "id": "S-001",',
    '  "phase": 1,',
    '  "priority": "P0",',
    '  "title": "Short imperative title",',
    '  "description": "Detailed description of what needs to be built",',
    '  "module": "auth",',
    '  "storyPoints": 5,',
    '  "dependencies": ["S-001"],',
    '  "acceptanceCriteria": [',
    '    {',
    '      "description": "User can log in with email and password",',
    '      "predicate": "authState is AuthStateAuthenticated"',
    '    }',
    '  ],',
    '  "passes": false',
    '}',
    '```',
    '',
    '## Fields',
    '',
    '| Field | Type | Description |',
    '|-------|------|-------------|',
    '| `id` | string | Unique story identifier (e.g., "S-001") |',
    '| `phase` | number | Implementation phase (1=core, 2=features, 3=polish, 4=advanced) |',
    '| `priority` | string | P0 (critical), P1 (high), P2 (medium), P3 (low) |',
    '| `title` | string | Short description of what to implement |',
    '| `description` | string | Full requirements and context |',
    '| `module` | string | Feature module this story belongs to (e.g., "auth", "api") |',
    '| `storyPoints` | number | Fibonacci estimate: 1, 2, 3, 5, 8, 13 |',
    '| `dependencies` | string[] | IDs of stories that must pass before this one starts |',
    '| `acceptanceCriteria` | object[] | Each has `description` (human) and `predicate` (machine-checkable) |',
    '| `passes` | boolean | `true` when story is complete and quality gates pass |',
    '',
    '## Workflow for Implementing a Story',
    '',
    '1. **Read the story**: Understand the description and acceptance criteria',
    '2. **Plan**: Identify which files need to be created or modified',
    '3. **Implement**: Follow Clean Architecture layers (domain → data → presentation)',
    '4. **Test**: Write unit/integration tests covering the acceptance criteria',
    '5. **Quality gates**: Run `flutter analyze && flutter test`',
    '6. **Mark complete**: Set `"passes": true` in `prd.json`',
    '7. **Commit**: `git commit -m "feat: [S-001] - Story title"`',
    '',
    '## Marking a Story Complete',
    '',
    'Only mark `passes: true` when:',
    '- All acceptance criteria are demonstrably met',
    '- `flutter analyze` returns zero errors or warnings',
    '- `flutter test` passes all tests',
    '- Code follows Clean Architecture layer rules',
  ].join('\n');
}

function generateSecurityReview(): string {
  return [
    '---',
    'model: sonnet',
    'user-invocable: true',
    'description: >-',
    '  Run a security audit. Triggers on: security review, check for vulnerabilities,',
    '  audit secrets, scan for security issues.',
    '---',
    '',
    '# Security Review Checklist',
    '',
    'Run a security audit of the current feature or codebase. Check each category and report findings.',
    '',
    '## 1. Secrets & Credentials Scanning',
    '',
    '- [ ] No hardcoded API keys, tokens, or passwords in source files',
    '- [ ] `.env` files are listed in `.gitignore`',
    '- [ ] Firebase `google-services.json` / `GoogleService-Info.plist` excluded from VCS',
    '- [ ] Secret values injected via CI environment variables, not committed',
    '',
    '## 2. Input Validation',
    '',
    '- [ ] All user input is validated before use (length, format, allowed characters)',
    '- [ ] Input validation applied at the domain layer, not just in UI widgets',
    '- [ ] No raw `eval`-equivalent construction from user strings',
    '- [ ] Form fields use `validator` callbacks with strict rules',
    '',
    '## 3. API Security',
    '',
    '- [ ] All API requests use HTTPS; no plain HTTP endpoints',
    '- [ ] Authentication headers (Bearer tokens) sent on every authenticated request',
    '- [ ] API responses are validated against expected schemas before use',
    '- [ ] Network timeouts configured to prevent hanging requests',
    '- [ ] Error responses do not leak stack traces or internal details to the UI',
    '',
    '## 4. Data Protection Audit',
    '',
    '- [ ] Sensitive data (tokens, PII) stored in `flutter_secure_storage`, not `SharedPreferences`',
    '- [ ] Sensitive data not logged to console or crash reporters',
    '- [ ] Deep link parameters sanitised before use in navigation or queries',
    '- [ ] User data deleted on logout (local cache, secure storage cleared)',
    '',
    '## Reporting',
    '',
    'For each finding, report:',
    '- **Severity**: Critical / High / Medium / Low',
    '- **Location**: File path and line number',
    '- **Description**: What the issue is and why it matters',
    '- **Fix**: Concrete code change to resolve it',
  ].join('\n');
}

function generatePerformanceCheck(): string {
  return [
    '---',
    'model: haiku',
    'user-invocable: true',
    'description: >-',
    '  Check for Flutter performance issues. Triggers on: performance check, check performance,',
    '  audit rebuilds, optimize widgets.',
    '---',
    '',
    '# Performance Check Checklist',
    '',
    'Audit the current feature for Flutter performance issues. Check each area and flag regressions.',
    '',
    '## 1. Widget Rebuild Detection',
    '',
    '- [ ] No unnecessary `setState` calls in parent widgets that repaint large subtrees',
    '- [ ] `const` constructors used wherever widget parameters are compile-time constants',
    '- [ ] `ConsumerWidget` / `Consumer` scoped as narrowly as possible to minimise rebuild area',
    '- [ ] `RepaintBoundary` wrapping expensive, frequently-animated widgets',
    '',
    '## 2. Provider Efficiency',
    '',
    '- [ ] `ref.watch` only used in `build()` — never inside callbacks or `initState`',
    '- [ ] `.autoDispose` applied to providers not needed globally',
    '- [ ] `select()` used to subscribe to a sub-field, avoiding full-state rebuilds',
    '- [ ] No provider created inside a `build()` method (causes re-creation each frame)',
    '',
    '## 3. Image & Asset Optimisation',
    '',
    '- [ ] All images served in WebP or AVIF format where possible',
    '- [ ] `cached_network_image` (or equivalent) used for remote images',
    '- [ ] Large images resized to display dimensions — no 4K image in a 48×48 avatar',
    '- [ ] SVG assets used for icons instead of raster PNGs where supported',
    '',
    '## 4. Lists & Scrolling Performance',
    '',
    '- [ ] `ListView.builder` used for any list with more than 20 items',
    '- [ ] `itemExtent` or `SliverFixedExtentList` set when item height is uniform',
    '- [ ] Heavy list items wrapped in `AutomaticKeepAliveClientMixin` only when truly needed',
    '- [ ] `Sliver` widgets used in complex scroll layouts instead of nested `ListView`',
    '',
    '## Reporting',
    '',
    'For each issue found:',
    '- **Widget / Provider**: Name and file path',
    '- **Problem**: Description of the performance issue',
    '- **Measured impact**: Frame time, rebuild count, or memory delta if measurable',
    '- **Fix**: Specific code change with before/after snippet',
  ].join('\n');
}

function generateQualityGate(): string {
  return [
    '---',
    'model: sonnet',
    'user-invocable: true',
    'description: >-',
    '  Run all quality checks. Triggers on: run quality checks, quality gate,',
    '  check code quality, run analysis.',
    '---',
    '',
    '# Quality Gate',
    '',
    'Run the full quality gate pipeline for this Flutter project.',
    '',
    '## Step 1 — Static Analysis',
    '',
    '```bash',
    'flutter analyze',
    '```',
    '',
    'Fix all errors and warnings before proceeding.',
    '',
    '## Step 2 — Code Formatting',
    '',
    '```bash',
    'dart format --set-exit-if-changed .',
    '```',
    '',
    'Ensure all files are properly formatted.',
    '',
    '## Step 3 — Run Tests',
    '',
    '```bash',
    'flutter test',
    '```',
    '',
    'All tests must pass. Fix any failures before proceeding.',
    '',
    '## Step 4 — Coverage Check',
    '',
    '```bash',
    'flutter test --coverage',
    '```',
    '',
    'Review coverage report. Aim for 80%+ statement and branch coverage.',
    'Write targeted tests for any uncovered critical paths.',
    '',
    '## Step 5 — Summary',
    '',
    'Report results:',
    '- **flutter analyze**: pass/fail (number of issues)',
    '- **dart format**: pass/fail',
    '- **flutter test**: pass/fail (number of tests)',
    '- **Coverage**: percentage and uncovered areas',
  ].join('\n');
}

function generateAddFeatureSkill(context: ProjectContext): string {
  const authGuardStep = context.modules.auth
    ? [
        '',
        '### Optional: Add Route Guard',
        '',
        'If the feature requires authentication:',
        '',
        '```dart',
        '// In app_router.dart redirect',
        'if (!ref.read(isLoggedInProvider) && state.matchedLocation == \'/<feature>\') {',
        '  return \'/auth/login\';',
        '}',
        '```',
      ].join('\n')
    : '';

  return [
    '---',
    'model: sonnet',
    '---',
    '',
    '# Add a New Clean Architecture Feature',
    '',
    'Follow these steps to add a new feature to this Flutter project. Replace `<name>` with the feature name (snake_case).',
    '',
    '## Step 1 — Create the domain layer',
    '',
    '```',
    'lib/features/<name>/domain/',
    '├── entities/        ← freezed data classes',
    '├── repositories/    ← abstract interfaces',
    '└── usecases/        ← single-responsibility operations',
    '```',
    '',
    'Define entities with `@freezed`, repository interfaces (abstract classes), and use cases.',
    '',
    '## Step 2 — Create the data layer',
    '',
    '```',
    'lib/features/<name>/data/',
    '├── models/          ← DTOs with fromJson/toJson',
    '├── datasources/     ← remote and local data sources',
    '└── repositories/    ← repository implementations',
    '```',
    '',
    '## Step 3 — Create the presentation layer',
    '',
    '```',
    'lib/features/<name>/presentation/',
    '├── providers/       ← Riverpod AsyncNotifierProvider',
    '├── pages/           ← full-screen route targets',
    '└── widgets/         ← reusable UI components',
    '```',
    '',
    '## Step 4 — Run code generation',
    '',
    '```bash',
    'dart run build_runner build --delete-conflicting-outputs',
    '```',
    '',
    '## Step 5 — Register routes',
    '',
    'Add `@TypedGoRoute` annotation in `lib/core/router/app_router.dart` and re-run build_runner.',
    authGuardStep,
    '',
    '## Step 6 — Register providers',
    '',
    'Export new providers from `lib/features/<name>/presentation/providers/<name>_provider.dart`.',
    '',
    '## Step 7 — Write tests',
    '',
    '```',
    'test/features/<name>/',
    '├── domain/          ← entity and use case unit tests',
    '├── data/            ← repository and data source tests',
    '└── presentation/    ← widget and provider tests',
    '```',
    '',
    'Run: `flutter test test/features/<name>/`',
  ].join('\n');
}
