/**
 * Generates a prompt/template for decomposing user journeys into PRD stories.
 * This prompt is embedded in the plan-app skill to instruct Claude on how
 * to break each user journey into domain → data → presentation → tests layers.
 */
export function generateJourneyDecompositionPrompt(journeys: string[]): string {
  const journeyList =
    journeys.length > 0
      ? journeys.map((j, i) => `${i + 1}. ${j}`).join('\n')
      : '_No journeys provided. Identify user journeys from the project brief first._';

  return [
    '# Journey-to-Stories Decomposition',
    '',
    'Decompose each user journey into PRD stories following Clean Architecture layers.',
    '',
    '## User Journeys to Decompose',
    '',
    journeyList,
    '',
    '## Decomposition Rules',
    '',
    'For each journey, create 2-4 stories following this layer order:',
    '',
    '1. **Domain story** — entities, repository interfaces, use cases (no dependencies)',
    '2. **Data story** — models, data sources, repository implementations (depends on domain story)',
    '3. **Presentation story** — providers, pages, widgets (depends on domain story)',
    '4. **Tests story** (optional) — integration and widget tests for the full feature',
    '',
    '### Dependency Chain',
    '',
    'Always maintain this dependency ordering:',
    '',
    '```',
    'domain ← data ← presentation ← tests',
    '```',
    '',
    '- Domain story has no dependencies',
    '- Data story depends on domain story',
    '- Presentation story depends on domain story',
    '- Tests story depends on presentation story (and implicitly all others)',
    '',
    '## Story Format',
    '',
    'Each story must follow this structure:',
    '',
    '```json',
    '{',
    '  "phase": <number>,',
    '  "priority": "P0" | "P1" | "P2",',
    '  "title": "<imperative verb> <domain concept>",',
    '  "description": "<detailed implementation requirements>",',
    '  "layer": "domain" | "data" | "presentation" | "tests",',
    '  "storyPoints": <Fibonacci: 1, 2, 3, 5, 8>,',
    '  "dependencies": ["<story-id>"],',
    '  "acceptanceCriteria": [',
    '    {',
    '      "description": "<human-readable criterion>",',
    '      "predicate": "<machine-checkable assertion>"',
    '    }',
    '  ]',
    '}',
    '```',
    '',
    '## Acceptance Criteria Requirements',
    '',
    '- Each story must have >= 3 acceptance criteria',
    '- Every criterion must include a `predicate` field (machine-checkable assertion)',
    '- Predicates must be specific and testable (e.g., "authState is AuthStateAuthenticated")',
    '- Predicates use present tense: "UserEntity has id, email, name fields"',
    '',
    '## Story Points (Fibonacci)',
    '',
    '| Layer | Typical Points |',
    '|-------|---------------|',
    '| Domain | 2-3 |',
    '| Data | 3-5 |',
    '| Presentation | 3-8 |',
    '| Tests | 1-3 |',
    '',
    'Valid values: 1, 2, 3, 5, 8 (Fibonacci sequence only)',
    '',
    '## Example Output',
    '',
    'For journey "User signs up and logs in":',
    '',
    '1. **Domain** (3pts): Define Auth entities and repository interface',
    '   - `AuthRepository` abstract class with `signUp`, `signIn`, `signOut`',
    '   - `User` entity with freezed',
    '   - No dependencies',
    '',
    '2. **Data** (5pts): Implement auth data source and repository',
    '   - `AuthDataSourceImpl` connecting to backend',
    '   - `AuthRepositoryImpl` implementing domain interface',
    '   - Depends on domain story',
    '',
    '3. **Presentation** (5pts): Build login and register screens',
    '   - `LoginPage` and `RegisterPage` with ConsumerWidget',
    '   - `authNotifierProvider` with AsyncNotifier',
    '   - Depends on domain story',
    '',
    '4. **Tests** (2pts): Integration tests for auth flows',
    '   - Happy path sign-up and login flow',
    '   - Depends on presentation story',
    '',
    '## Output',
    '',
    'Return a JSON array of story objects for all journeys.',
    'Maintain dependency ordering within each journey\'s stories.',
    'Ensure every story ID is unique and referenced correctly in dependencies.',
  ].join('\n');
}
